services:
  app:
    image: movie-manager
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:h2:mem:moviedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - QUARKUS_DATASOURCE_USERNAME=sa
      - QUARKUS_DATASOURCE_PASSWORD=
    restart: unless-stopped
